// Simulated patient data with more details
export const patients = [
  {
    dni: "12345678A",
    nombre: "Juan Pérez",
    edad: 35,
    grupoSanguineo: "A+",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Diabetes",
    eps: "Sura",
    telefono: "3001234567",
    telefonoFamiliar: "3107654321",
  },
  {
    dni: "87654321B",
    nombre: "María López",
    edad: 28,
    grupoSanguineo: "O-",
    aceptaDonacion: false,
    razonNoTransfusional: "Testigo de Jehová",
    sexo: "Femenino",
    enfermedades: "Hipotiroidismo",
    eps: "Coomeva",
    telefono: "3123456789",
    telefonoFamiliar: "3218765432",
  },
  {
    dni: "11223344C",
    nombre: "Carlos García",
    edad: 45,
    grupoSanguineo: "B+",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Hipertensión",
    eps: "Sanitas",
    telefono: "3012345678",
    telefonoFamiliar: "3201234567",
  },
  {
    dni: "44332211D",
    nombre: "Ana Martínez",
    edad: 52,
    grupoSanguineo: "AB-",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Femenino",
    enfermedades: "Colesterol alto",
    eps: "Compensar",
    telefono: "3145678912",
    telefonoFamiliar: "3182345678",
  },
  {
    dni: "55667788E",
    nombre: "Pedro Sánchez",
    edad: 39,
    grupoSanguineo: "A-",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Asma",
    eps: "Nueva EPS",
    telefono: "3056781234",
    telefonoFamiliar: "3103456789",
  },
  {
    dni: "99887766F",
    nombre: "Laura Torres",
    edad: 30,
    grupoSanguineo: "O+",
    aceptaDonacion: true,
    sexo: "Femenino",
    enfermedades: "Artritis",
    eps: "Salud Total",
    telefono: "3156789123",
    telefonoFamiliar: "3205678901",
  },
  {
    dni: "22113344G",
    nombre: "Luis Gutiérrez",
    edad: 42,
    grupoSanguineo: "B-",
    aceptaDonacion: false,
    razonNoTransfusional: "Creencias religiosas",
    sexo: "Masculino",
    enfermedades: "Diabetes tipo 2",
    eps: "Medimás",
    telefono: "3045678912",
    telefonoFamiliar: "3112345678",
  },
  {
    dni: "33445566H",
    nombre: "Sandra Ramírez",
    edad: 25,
    grupoSanguineo: "A+",
    aceptaDonacion: true,
    sexo: "Femenino",
    enfermedades: "Ninguna",
    eps: "Famisanar",
    telefono: "3009876543",
    telefonoFamiliar: "3158765432",
  },
  {
    dni: "77889900I",
    nombre: "Roberto Díaz",
    edad: 58,
    grupoSanguineo: "O-",
    aceptaDonacion: false,
    razonNoTransfusional: "Testigo de Jehová",
    sexo: "Masculino",
    enfermedades: "Problemas cardíacos",
    eps: "Sura",
    telefono: "3182345678",
    telefonoFamiliar: "3192345678",
  },
  {
    dni: "55664477J",
    nombre: "Beatriz Morales",
    edad: 67,
    grupoSanguineo: "AB+",
    aceptaDonacion: true,
    sexo: "Femenino",
    enfermedades: "Osteoporosis",
    eps: "Cafesalud",
    telefono: "3014567890",
    telefonoFamiliar: "3106789012",
  },
  {
    dni: "11224466K",
    nombre: "Fernando Núñez",
    edad: 33,
    grupoSanguineo: "B+",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Masculino",
    enfermedades: "Enfermedad renal",
    eps: "Salud Total",
    telefono: "3056789012",
    telefonoFamiliar: "3223456789",
  },
  {
    dni: "22998833L",
    nombre: "Gloria Espinoza",
    edad: 36,
    grupoSanguineo: "A-",
    aceptaDonacion: true,
    sexo: "Femenino",
    enfermedades: "Epilepsia",
    eps: "Sanitas",
    telefono: "3175678901",
    telefonoFamiliar: "3245678901",
  },
  {
    dni: "66778899M",
    nombre: "Javier Suárez",
    edad: 50,
    grupoSanguineo: "O+",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Masculino",
    enfermedades: "Problemas hepáticos",
    eps: "Compensar",
    telefono: "3162345678",
    telefonoFamiliar: "3256789012",
  },
  {
    dni: "22334455N",
    nombre: "Patricia Castro",
    edad: 29,
    grupoSanguineo: "A+",
    aceptaDonacion: true,
    sexo: "Femenino",
    enfermedades: "Ninguna",
    eps: "Sura",
    telefono: "3198765432",
    telefonoFamiliar: "3005671234",
  },
  {
    dni: "99886655O",
    nombre: "Alberto Herrera",
    edad: 47,
    grupoSanguineo: "B-",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Hipertensión",
    eps: "Coomeva",
    telefono: "3003456789",
    telefonoFamiliar: "3129876543",
  },
  {
    dni: "55332244P",
    nombre: "Natalia Pérez",
    edad: 39,
    grupoSanguineo: "AB+",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Femenino",
    enfermedades: "Asma",
    eps: "Nueva EPS",
    telefono: "3173456789",
    telefonoFamiliar: "3201239876",
  },
  {
    dni: "66779988Q",
    nombre: "Guillermo Ortiz",
    edad: 34,
    grupoSanguineo: "O-",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Ninguna",
    eps: "Medimás",
    telefono: "3185672345",
    telefonoFamiliar: "3109876543",
  },
  {
    dni: "11223377R",
    nombre: "Silvia Gómez",
    edad: 55,
    grupoSanguineo: "A-",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Femenino",
    enfermedades: "Problemas respiratorios",
    eps: "Cafesalud",
    telefono: "3009871234",
    telefonoFamiliar: "3198765432",
  },
  {
    dni: "44331122S",
    nombre: "Mario Jiménez",
    edad: 62,
    grupoSanguineo: "B+",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Artritis",
    eps: "Famisanar",
    telefono: "3221234567",
    telefonoFamiliar: "3107654321",
  },
  {
    dni: "77445566T",
    nombre: "Andrea Martínez",
    edad: 37,
    grupoSanguineo: "O+",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Femenino",
    enfermedades: "Ninguna",
    eps: "Salud Total",
    telefono: "3112345678",
    telefonoFamiliar: "3134567890",
  },
  {
    dni: "99002233U",
    nombre: "Pablo Herrera",
    edad: 49,
    grupoSanguineo: "A+",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Colesterol alto",
    eps: "Compensar",
    telefono: "3003456789",
    telefonoFamiliar: "3209876543",
  },
  {
    dni: "11335577V",
    nombre: "Carla Rodríguez",
    edad: 27,
    grupoSanguineo: "AB-",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Femenino",
    enfermedades: "Migraña",
    eps: "Sura",
    telefono: "3201234567",
    telefonoFamiliar: "3156789012",
  },
  {
    dni: "22446655W",
    nombre: "Diego Vázquez",
    edad: 53,
    grupoSanguineo: "B+",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Diabetes",
    eps: "Coomeva",
    telefono: "3198765432",
    telefonoFamiliar: "3123456789",
  },
  {
    dni: "77889922X",
    nombre: "Inés Ramírez",
    edad: 41,
    grupoSanguineo: "O-",
    aceptaDonacion: false,
    razonNoTransfusional: "Condición médica",
    sexo: "Femenino",
    enfermedades: "Problemas cardíacos",
    eps: "Nueva EPS",
    telefono: "3145678901",
    telefonoFamiliar: "3201234567",
  },
  {
    dni: "33445522Y",
    nombre: "Joaquín Ortega",
    edad: 60,
    grupoSanguineo: "A-",
    aceptaDonacion: true,
    sexo: "Masculino",
    enfermedades: "Colesterol alto",
    eps: "Medimás",
    telefono: "3182345678",
    telefonoFamiliar: "3156789012",
  },
];

export const patientsPerPage = 10;

export const faqs = [
  {
    question: "¿Qué debo hacer en casos de emergencia?",
    answer:
      "En casos de emergencia, siga el protocolo establecido por el hospital. Acceda rápidamente a la información del paciente a través de la sección de 'Acceso de Emergencia' en el dashboard. Asegúrese de verificar las restricciones de transfusión y alergias antes de cualquier procedimiento.",
  },
  {
    question:
      "¿Cómo manejo a un paciente que no acepta transfusiones de sangre?",
    answer:
      "Para pacientes que no aceptan transfusiones de sangre, considere alternativas como el uso de factores de coagulación, eritropoyetina, o técnicas de conservación de sangre. Consulte con el comité de ética del hospital si es necesario. Siempre respete las decisiones del paciente y busque el mejor curso de acción alternativo.",
  },
  {
    question: "¿Cómo actualizo la información de un paciente?",
    answer:
      "Para actualizar la información de un paciente, vaya a su perfil haciendo clic en el botón 'Consultar' en la tabla de pacientes. Luego, seleccione la opción 'Editar información' en la ventana emergente. Asegúrese de guardar los cambios y verificar que la información actualizada se refleje correctamente en el sistema.",
  },
  {
    question: "¿Qué hago si encuentro un error en los datos de un paciente?",
    answer:
      "Si encuentra un error en los datos de un paciente, primero verifique la información con el paciente o sus registros físicos. Luego, siga el proceso de actualización de información mencionado anteriormente. Si el error es crítico y puede afectar el tratamiento inmediato, notifique a su supervisor y al departamento de registros médicos de inmediato.",
  },
];
